# Generated by Django 6.0.3 on 2026-03-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfflineSale',
        ),
    ]
