# Generated by Django 6.0.3 on 2026-03-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hr', '0002_delete_offlinesale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
