# Generated by Django 6.0.3 on 2026-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hr', '0003_delete_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
