# Generated by Django 5.2.3 on 2025-06-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0003_alter_category_name_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='admin_photos/')),
                ('address', models.TextField()),
            ],
        ),
    ]
