# Generated by Django 5.2.8 on 2026-03-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ap_1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ap_1.product')),
            ],
        ),
    ]
