# Generated by Django 6.0.3 on 2026-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0013_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory')], max_length=50)),
            ],
        ),
    ]
