# Generated by Django 6.0.3 on 2026-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0020_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
