# Generated by Django 6.0.3 on 2026-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0021_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
