# Generated by Django 6.0.3 on 2026-03-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0023_foodcart_foodcartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentotp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentotp',
            name='user',
        ),
        migrations.CreateModel(
            name='FoodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqt'), ('card', 'Karta')], max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_ap_1.foodorder')),
            ],
        ),
    ]
