# Generated by Django 6.0.3 on 2026-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0024_remove_paymentotp_created_at_remove_paymentotp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='address',
            field=models.CharField(default='Toshkent', max_length=255),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='estimated_time',
            field=models.IntegerField(default=25),
        ),
    ]
