# Generated by Django 6.0.3 on 2026-04-03 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap_1', '0028_alter_profile_role_distributorsupplier_supplierorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
